#config
url: http://gsa-ocsit.github.io/mygov-bar #url to site
api_url: https://discovery.my.usa.gov #url to backend
search_affiliate: mygov-bar
version: '2.0.8'
width_minimized: '45'
minWidth: 650
trigger: '0'
tabs:
  - search
  - related
  - expand
  - close
  - feedback
  - mygov
animation_speed: 500 #milliseconds

#build config
exclude: [ 'Cakefile', 'package.json', 'Gruntfile.coffee', 'readme.md', 'node_modules', 'test' ]
