#config
url: http://gsa-ocsit.github.com/mygov-bar #url to site
api_url: http://staging.discovery.my.usa.gov #url to backend
search_affiliate: mygov-bar
version: 0.1 #used to break static asset cache
widthMinimized: '40%'
minWidth: 650
trigger: '75'
tabs:
  - search
  - related
  - tags
  - feedback
  - mygov
animation_speed: 1000 #miliseconds

#build config
server: true
auto: true
exclude: [ 'Cakefile', 'package.json', 'readme.md' ]