#config
#url: http://gsa-ocsit.github.com/mygov-bar #url to site
url: http://localhost:4000
api_url: http://localhost:3000 #url to backend
search_affiliate: mygov-bar
version: '1.0.4'
minWidth: 650
trigger: '0'
tabs:
  - search
  - related
  - expand
  - close
  - tags
  - feedback
  - mygov
animation_speed: 500 #miliseconds

#build config
exclude: [ 'Cakefile', 'package.json', 'Gruntfile.coffee', 'readme.md', 'node_modules', 'test' ]
