#config
url: http://gsa-ocsit.github.com/mygov-bar #url to site
api_url: http://discovery.my.usa.gov #url to backend
search_affiliate: mygov-bar
version: '1.9.6'
width_minimized: '45'
minWidth: 650
trigger: '0'
tabs:
  - search
  - related
  - expand
  - close
  - tags
  - feedback
  - mygov
animation_speed: 500 #milliseconds

#build config
exclude: [ 'Cakefile', 'package.json', 'Gruntfile.coffee', 'readme.md', 'node_modules', 'test' ]
