#config
url: http://gsa-ocsit.github.com/mygov-bar #url to site
api_url: http://staging.discovery.my.usa.gov #url to backend
search_affiliate: mygov-bar
version: 0.1 #used to break static asset cache
widthMinimized: '30%'
minWidth: 650
trigger: '75'
tabs:
  - search
  - related
  - expand
  - close
  - tags
  - feedback
  - mygov
animation_speed: 500 #miliseconds

#build config
exclude: [ 'Cakefile', 'package.json', 'Gruntfile.coffee', 'readme.md', 'node_modules', 'test' ]