#config
url: http://localhost:4000 #url to site
api_url: http://localhost:1234 #url to backend
search_affiliate: mygov-bar
version: '2.2.3'
width_minimized: '45'
minWidth: 650
trigger: '0'
tabs:
  - search
  - related
  - expand
  - close
  - feedback
  - mygov
animation_speed: 500 #milliseconds

#build config
exclude: [ 'Cakefile', 'package.json', 'Gruntfile.coffee', 'readme.md', 'node_modules', 'test' ]
